server:
  port: 8061

eureka:
  instance:
    hostname: eurekaserver10
    appname: eureka-server
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
#    statusPageUrl: http://${eureka.hostname}/info
#    healthCheckUrl: http://${eureka.hostname}/health
#    homePageUrl: http://${eureka.hostname}/home
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  context-path: /manager