server:
  port: 8062

eureka:
  instance:
    appname: eurekaservice1
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      #${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8061/eureka/

      #http://eurekaserver10:8061/eureka/,http://eurekaserver20:8071/eureka/,http://eurekaserver30:8081/eureka/

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
  level: DEBUG