server:
  port: 8062

eureka:
  instance:
    appname: eurekaservice10
    hostname: eurekaservice11
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      #${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/