server:
  port: 8069
  context-path: /api

security:
  user:
    name: user
    password: password
#  ignored: /css/**,/js/**,/favicon.ico,/webjars/**
#  oauth2:
#    client:
#      access-token-uri: #指定获取access token的URI.
#      user-authorization-uri:
#      access-token-validity-seconds:  #指定access token失效时长.
#      refresh-token-validity-seconds:

eureka:
  instance:
    appname: securityservice
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      #${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8061/eureka/
      #http://eurekaserver10:8061/eureka/,http://eurekaserver20:8071/eureka/,http://eurekaserver30:8081/eureka/

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.security: DEBUG
  level: DEBUG
